services:
  - type: web
    name: gravitational-anomaly-mapper
    env: node
    plan: free
    buildCommand: |
      # Create necessary directories
      mkdir -p dist
      mkdir -p dist/public
      
      # Install dependencies
      npm ci
      cd client && npm ci
      cd ../server && npm ci
      cd ../shared && npm ci
      cd ..
      
      # Build client
      npx vite build
      
      # Build server
      npx esbuild server/index.ts server/routes.ts server/storage.ts server/vite.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true